config/routes.rb
Rails.application.routes.draw do
  resources :food_items
	get 'contact_us' => 'home#contact_us'
	get 'menu' => 'home#menu'
	get 'food_items' => 'food_items#index'
	root 'home#index'

	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	validates :name, :section, :price, presence: true

	def image_url
		if remote_image_url.present?
			remote_image_url
		else
			"http://loremflickr.com/320/240/#{CGI.escape name}"
		end
	end
end

app/models/section.rb
class Section
	def self.all
		%w(Breakfast Lunch Dinner Supper)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section, :remote_image_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end
  
  def menu
  	if params[:section]
  		@food_items = FoodItem.where section: params[:section]
  	else
  		@food_items = FoodItem.all
  	end

    if params[:sort_column]
      @food_items = @food_items.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-control-label' %>
    <%= form.text_field :name, id: :food_item_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description, class: 'form-control-label'%>
    <%= form.text_area :description, id: :food_item_description, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :section %>
    <%= form.text_field :section, id: :food_item_section %>
  </div>

  <div class="field">
    <%= form.label :remote_image_url %>
    <%= form.text_field :remote_image_url, id: :food_item_remote_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-striped">
  <thead class="thead thead-default">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Remote image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= image_tag food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path, class: 'btn btn-secondary' %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section %>
</p>

<p>
  <strong>Remote image url:</strong>
  <%= @food_item.remote_image_url %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<h1>Where we are?</h1>

<div class="row">
	<div class="col-xs-3">
		<h3>Address</h3>
		<address>
			Tamaulipas 50<br>
			Centro<br>
			37800 Dolores Hidalgo Cuna de la Independencia Nacional, Gto.<br>
		</address>
	</div>
	<div class="col-xs-9">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3720.8878326101176!2d-100.93234028517061!3d21.1568616887689!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b3f060c76db23%3A0xa52c80d600c485ff!2sTamaulipas+50%2C+Centro%2C+37800+Dolores+Hidalgo+Cuna+de+la+Independencia+Nacional%2C+Gto.!5e0!3m2!1ses!2smx!4v1502087322117" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">The best Restaurant Ever!</h1>
  <p class="lead">You come here to eat</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <%= link_to "Menu", menu_path, class: 'btn btn-secondary btn-lg'%>
    <%= link_to "Contact Us", contact_us_path, class: 'btn btn-secondary btn-lg'%>
  </p>
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>
<!-- Por que al poner "=" en "<%= %>" sale el texto fuera de los botones?-->
<% Section.all.each do |section| %>

	<div class="btn-group" role="group" aria-label="Basic example">
	  <%= link_to section, menu_path(section: section), class: 'btn btn-secondary' %>
	</div>
<% end %>

<div class="card card-block">
	<%= form_tag nil, method: 'get' do %>
	<div class="form-inline">
		<%= select_tag :sort_column, options_for_select([['Nombre','name'], ['Precio', 'price']]), class: 'form-control'%>
		<%= select_tag :sort_direction, options_for_select([['Ascendiente','asc'], ['Descendiente','desc']]), class: 'form-control'%>
		<%= submit_tag "Sort", class: "btn btn-secondary" %>
		</div>
	<% end %>
</div>

<% @food_items.each do |food_item| %>
		<div class="card">
			<div class="card-header">
				<%= food_item.name %>, $<%= food_item.price %>
			</div>
			<div class="card-block">
				<%= image_tag food_item.image_url %>
			</div>
		</div>
<% end %>

<%= link_to "Add Food", food_items_path, class: 'btn btn-secondary btn-lg'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	 <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
	  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>
	  <a class="navbar-brand" href="#">Navbar</a>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item <%= 'active' if current_page?(root_path) %>">
	        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item <%= 'active' if current_page?(menu_path) %>">
	      	<%= link_to "Menu", menu_path, class: 'nav-link' %>
	      </li>
	      <li class="nav-item <%= 'active' if current_page?(contact_us_path) %>">
	      	<%= link_to "Contact Us", contact_us_path, class: 'nav-link' %>
	      </li>
	    </ul>
	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="text" placeholder="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form>
	  </div>
	</nav>
	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>